// control.proto — SYNCED copy of the RF-instrument firmware control protocol.
//
// The CANONICAL definition lives in the firmware repo
// (github.com/OcupointInc/wiznet-ethernet-firmware, examples/dhcp_dns/control.proto).
// This copy exists so the rf-control Go library can generate its own bindings;
// keep it byte-for-byte identical to the canonical file EXCEPT the go_package
// line below. After syncing, regenerate the Go bindings:
//
//   protoc -I. --go_out=. --go_opt=module=github.com/OcupointInc/rf-control control.proto
//
// Do not hand-edit controlpb/control.pb.go.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: control.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums for each switch bank
type RfSwitchOption int32

const (
	RfSwitchOption_RF_SWITCH_OPTION_4GHZ_LPF RfSwitchOption = 0
	RfSwitchOption_RF_SWITCH_OPTION_2GHZ_LPF RfSwitchOption = 1
)

// Enum value maps for RfSwitchOption.
var (
	RfSwitchOption_name = map[int32]string{
		0: "RF_SWITCH_OPTION_4GHZ_LPF",
		1: "RF_SWITCH_OPTION_2GHZ_LPF",
	}
	RfSwitchOption_value = map[string]int32{
		"RF_SWITCH_OPTION_4GHZ_LPF": 0,
		"RF_SWITCH_OPTION_2GHZ_LPF": 1,
	}
)

func (x RfSwitchOption) Enum() *RfSwitchOption {
	p := new(RfSwitchOption)
	*p = x
	return p
}

func (x RfSwitchOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RfSwitchOption) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[0].Descriptor()
}

func (RfSwitchOption) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[0]
}

func (x RfSwitchOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RfSwitchOption.Descriptor instead.
func (RfSwitchOption) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

type MixerSwitchOption int32

const (
	MixerSwitchOption_MIXER_SWITCH_OPTION_MIXER  MixerSwitchOption = 0
	MixerSwitchOption_MIXER_SWITCH_OPTION_BYPASS MixerSwitchOption = 1
)

// Enum value maps for MixerSwitchOption.
var (
	MixerSwitchOption_name = map[int32]string{
		0: "MIXER_SWITCH_OPTION_MIXER",
		1: "MIXER_SWITCH_OPTION_BYPASS",
	}
	MixerSwitchOption_value = map[string]int32{
		"MIXER_SWITCH_OPTION_MIXER":  0,
		"MIXER_SWITCH_OPTION_BYPASS": 1,
	}
)

func (x MixerSwitchOption) Enum() *MixerSwitchOption {
	p := new(MixerSwitchOption)
	*p = x
	return p
}

func (x MixerSwitchOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MixerSwitchOption) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[1].Descriptor()
}

func (MixerSwitchOption) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[1]
}

func (x MixerSwitchOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MixerSwitchOption.Descriptor instead.
func (MixerSwitchOption) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

type IfSwitchOption int32

const (
	IfSwitchOption_IF_SWITCH_OPTION_900MHZ_LPF      IfSwitchOption = 0
	IfSwitchOption_IF_SWITCH_OPTION_1_2GHZ_BANDPASS IfSwitchOption = 1
)

// Enum value maps for IfSwitchOption.
var (
	IfSwitchOption_name = map[int32]string{
		0: "IF_SWITCH_OPTION_900MHZ_LPF",
		1: "IF_SWITCH_OPTION_1_2GHZ_BANDPASS",
	}
	IfSwitchOption_value = map[string]int32{
		"IF_SWITCH_OPTION_900MHZ_LPF":      0,
		"IF_SWITCH_OPTION_1_2GHZ_BANDPASS": 1,
	}
)

func (x IfSwitchOption) Enum() *IfSwitchOption {
	p := new(IfSwitchOption)
	*p = x
	return p
}

func (x IfSwitchOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IfSwitchOption) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[2].Descriptor()
}

func (IfSwitchOption) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[2]
}

func (x IfSwitchOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IfSwitchOption.Descriptor instead.
func (IfSwitchOption) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

// Enum for RF bands
type RfBand int32

const (
	RfBand_RF_BAND_10_900MHZ    RfBand = 0
	RfBand_RF_BAND_900_1800MHZ  RfBand = 1
	RfBand_RF_BAND_1800_2700MHZ RfBand = 2
	RfBand_RF_BAND_2700_3600MHZ RfBand = 3
	RfBand_RF_BAND_3600_4500MHZ RfBand = 4
)

// Enum value maps for RfBand.
var (
	RfBand_name = map[int32]string{
		0: "RF_BAND_10_900MHZ",
		1: "RF_BAND_900_1800MHZ",
		2: "RF_BAND_1800_2700MHZ",
		3: "RF_BAND_2700_3600MHZ",
		4: "RF_BAND_3600_4500MHZ",
	}
	RfBand_value = map[string]int32{
		"RF_BAND_10_900MHZ":    0,
		"RF_BAND_900_1800MHZ":  1,
		"RF_BAND_1800_2700MHZ": 2,
		"RF_BAND_2700_3600MHZ": 3,
		"RF_BAND_3600_4500MHZ": 4,
	}
)

func (x RfBand) Enum() *RfBand {
	p := new(RfBand)
	*p = x
	return p
}

func (x RfBand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RfBand) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[3].Descriptor()
}

func (RfBand) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[3]
}

func (x RfBand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RfBand.Descriptor instead.
func (RfBand) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

// Reason a request could not be completed (see ErrorResponse).
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED     ErrorCode = 0
	ErrorCode_ERROR_CODE_UNSUPPORTED     ErrorCode = 1 // unknown message id, or a feature this board/firmware lacks
	ErrorCode_ERROR_CODE_DECODE_FAILED   ErrorCode = 2 // the request packet failed to decode
	ErrorCode_ERROR_CODE_INVALID_REQUEST ErrorCode = 3 // arguments out of range / malformed
	ErrorCode_ERROR_CODE_HARDWARE_ERROR  ErrorCode = 4 // the underlying device operation failed
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_UNSUPPORTED",
		2: "ERROR_CODE_DECODE_FAILED",
		3: "ERROR_CODE_INVALID_REQUEST",
		4: "ERROR_CODE_HARDWARE_ERROR",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":     0,
		"ERROR_CODE_UNSUPPORTED":     1,
		"ERROR_CODE_DECODE_FAILED":   2,
		"ERROR_CODE_INVALID_REQUEST": 3,
		"ERROR_CODE_HARDWARE_ERROR":  4,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[4].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[4]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

type SetPllFrequencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FrequencyMhz  int32                  `protobuf:"varint,1,opt,name=frequency_mhz,json=frequencyMhz,proto3" json:"frequency_mhz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPllFrequencyRequest) Reset() {
	*x = SetPllFrequencyRequest{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPllFrequencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPllFrequencyRequest) ProtoMessage() {}

func (x *SetPllFrequencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPllFrequencyRequest.ProtoReflect.Descriptor instead.
func (*SetPllFrequencyRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *SetPllFrequencyRequest) GetFrequencyMhz() int32 {
	if x != nil {
		return x.FrequencyMhz
	}
	return 0
}

type SetRfBandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Band          RfBand                 `protobuf:"varint,1,opt,name=band,proto3,enum=control.RfBand" json:"band,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRfBandRequest) Reset() {
	*x = SetRfBandRequest{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRfBandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRfBandRequest) ProtoMessage() {}

func (x *SetRfBandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRfBandRequest.ProtoReflect.Descriptor instead.
func (*SetRfBandRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *SetRfBandRequest) GetBand() RfBand {
	if x != nil {
		return x.Band
	}
	return RfBand_RF_BAND_10_900MHZ
}

type SetSwitchesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RfSwitch      RfSwitchOption         `protobuf:"varint,1,opt,name=rf_switch,json=rfSwitch,proto3,enum=control.RfSwitchOption" json:"rf_switch,omitempty"`
	MixerSwitch   MixerSwitchOption      `protobuf:"varint,2,opt,name=mixer_switch,json=mixerSwitch,proto3,enum=control.MixerSwitchOption" json:"mixer_switch,omitempty"`
	IfSwitch      IfSwitchOption         `protobuf:"varint,3,opt,name=if_switch,json=ifSwitch,proto3,enum=control.IfSwitchOption" json:"if_switch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSwitchesRequest) Reset() {
	*x = SetSwitchesRequest{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSwitchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSwitchesRequest) ProtoMessage() {}

func (x *SetSwitchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSwitchesRequest.ProtoReflect.Descriptor instead.
func (*SetSwitchesRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *SetSwitchesRequest) GetRfSwitch() RfSwitchOption {
	if x != nil {
		return x.RfSwitch
	}
	return RfSwitchOption_RF_SWITCH_OPTION_4GHZ_LPF
}

func (x *SetSwitchesRequest) GetMixerSwitch() MixerSwitchOption {
	if x != nil {
		return x.MixerSwitch
	}
	return MixerSwitchOption_MIXER_SWITCH_OPTION_MIXER
}

func (x *SetSwitchesRequest) GetIfSwitch() IfSwitchOption {
	if x != nil {
		return x.IfSwitch
	}
	return IfSwitchOption_IF_SWITCH_OPTION_900MHZ_LPF
}

// Request messages
type SetCalibrationEnabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCalibrationEnabledRequest) Reset() {
	*x = SetCalibrationEnabledRequest{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCalibrationEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCalibrationEnabledRequest) ProtoMessage() {}

func (x *SetCalibrationEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCalibrationEnabledRequest.ProtoReflect.Descriptor instead.
func (*SetCalibrationEnabledRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *SetCalibrationEnabledRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// Calibration source select (whalepod CAL_SEL line). The internal noise-source
// amplifier is enabled by the firmware only when calibration mode is active AND
// the internal source is selected.
type SetCalSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Internal      bool                   `protobuf:"varint,1,opt,name=internal,proto3" json:"internal,omitempty"` // false = external cal (CAL_SEL low), true = internal (high)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCalSourceRequest) Reset() {
	*x = SetCalSourceRequest{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCalSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCalSourceRequest) ProtoMessage() {}

func (x *SetCalSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCalSourceRequest.ProtoReflect.Descriptor instead.
func (*SetCalSourceRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *SetCalSourceRequest) GetInternal() bool {
	if x != nil {
		return x.Internal
	}
	return false
}

type SetChannelsEnabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetChannelsEnabledRequest) Reset() {
	*x = SetChannelsEnabledRequest{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetChannelsEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetChannelsEnabledRequest) ProtoMessage() {}

func (x *SetChannelsEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetChannelsEnabledRequest.ProtoReflect.Descriptor instead.
func (*SetChannelsEnabledRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *SetChannelsEnabledRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetAttenuationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttenuationDb int32                  `protobuf:"varint,1,opt,name=attenuation_db,json=attenuationDb,proto3" json:"attenuation_db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAttenuationRequest) Reset() {
	*x = SetAttenuationRequest{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAttenuationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAttenuationRequest) ProtoMessage() {}

func (x *SetAttenuationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAttenuationRequest.ProtoReflect.Descriptor instead.
func (*SetAttenuationRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *SetAttenuationRequest) GetAttenuationDb() int32 {
	if x != nil {
		return x.AttenuationDb
	}
	return 0
}

// PE42582 SP8T switch board: select which channel (1..8) routes to the common
// port. 0 (or any out-of-range value) puts the switch in the all-off /
// all-isolated state. The matching front-panel LED tracks the selection.
type SetRfSwitchChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       int32                  `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRfSwitchChannelRequest) Reset() {
	*x = SetRfSwitchChannelRequest{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRfSwitchChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRfSwitchChannelRequest) ProtoMessage() {}

func (x *SetRfSwitchChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRfSwitchChannelRequest.ProtoReflect.Descriptor instead.
func (*SetRfSwitchChannelRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *SetRfSwitchChannelRequest) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

// Response messages
type SetCalibrationEnabledResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCalibrationEnabledResponse) Reset() {
	*x = SetCalibrationEnabledResponse{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCalibrationEnabledResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCalibrationEnabledResponse) ProtoMessage() {}

func (x *SetCalibrationEnabledResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCalibrationEnabledResponse.ProtoReflect.Descriptor instead.
func (*SetCalibrationEnabledResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

type SetCalSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCalSourceResponse) Reset() {
	*x = SetCalSourceResponse{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCalSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCalSourceResponse) ProtoMessage() {}

func (x *SetCalSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCalSourceResponse.ProtoReflect.Descriptor instead.
func (*SetCalSourceResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

type SetAttenuationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAttenuationResponse) Reset() {
	*x = SetAttenuationResponse{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAttenuationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAttenuationResponse) ProtoMessage() {}

func (x *SetAttenuationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAttenuationResponse.ProtoReflect.Descriptor instead.
func (*SetAttenuationResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

type SetChannelsEnabledResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetChannelsEnabledResponse) Reset() {
	*x = SetChannelsEnabledResponse{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetChannelsEnabledResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetChannelsEnabledResponse) ProtoMessage() {}

func (x *SetChannelsEnabledResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetChannelsEnabledResponse.ProtoReflect.Descriptor instead.
func (*SetChannelsEnabledResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

type SetSwitchesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSwitchesResponse) Reset() {
	*x = SetSwitchesResponse{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSwitchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSwitchesResponse) ProtoMessage() {}

func (x *SetSwitchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSwitchesResponse.ProtoReflect.Descriptor instead.
func (*SetSwitchesResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

type SetPllFrequencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPllFrequencyResponse) Reset() {
	*x = SetPllFrequencyResponse{}
	mi := &file_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPllFrequencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPllFrequencyResponse) ProtoMessage() {}

func (x *SetPllFrequencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPllFrequencyResponse.ProtoReflect.Descriptor instead.
func (*SetPllFrequencyResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{13}
}

type SetRfBandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRfBandResponse) Reset() {
	*x = SetRfBandResponse{}
	mi := &file_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRfBandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRfBandResponse) ProtoMessage() {}

func (x *SetRfBandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRfBandResponse.ProtoReflect.Descriptor instead.
func (*SetRfBandResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{14}
}

type SetRfSwitchChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRfSwitchChannelResponse) Reset() {
	*x = SetRfSwitchChannelResponse{}
	mi := &file_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRfSwitchChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRfSwitchChannelResponse) ProtoMessage() {}

func (x *SetRfSwitchChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRfSwitchChannelResponse.ProtoReflect.Descriptor instead.
func (*SetRfSwitchChannelResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{15}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{16}
}

type SetCalAttenuationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCalAttenuationResponse) Reset() {
	*x = SetCalAttenuationResponse{}
	mi := &file_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCalAttenuationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCalAttenuationResponse) ProtoMessage() {}

func (x *SetCalAttenuationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCalAttenuationResponse.ProtoReflect.Descriptor instead.
func (*SetCalAttenuationResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{17}
}

type SetFrontendAttenuationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFrontendAttenuationResponse) Reset() {
	*x = SetFrontendAttenuationResponse{}
	mi := &file_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFrontendAttenuationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFrontendAttenuationResponse) ProtoMessage() {}

func (x *SetFrontendAttenuationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFrontendAttenuationResponse.ProtoReflect.Descriptor instead.
func (*SetFrontendAttenuationResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{18}
}

type SaveConfigRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StaticIp           []byte                 `protobuf:"bytes,1,opt,name=static_ip,json=staticIp,proto3" json:"static_ip,omitempty"`
	StaticGateway      []byte                 `protobuf:"bytes,2,opt,name=static_gateway,json=staticGateway,proto3" json:"static_gateway,omitempty"`
	StaticSubnet       []byte                 `protobuf:"bytes,3,opt,name=static_subnet,json=staticSubnet,proto3" json:"static_subnet,omitempty"`
	MdnsHostname       string                 `protobuf:"bytes,4,opt,name=mdns_hostname,json=mdnsHostname,proto3" json:"mdns_hostname,omitempty"`
	EnableGatewayCheck bool                   `protobuf:"varint,6,opt,name=enable_gateway_check,json=enableGatewayCheck,proto3" json:"enable_gateway_check,omitempty"`
	MacAddress         []byte                 `protobuf:"bytes,7,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	SerialNumber       string                 `protobuf:"bytes,8,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SaveConfigRequest) Reset() {
	*x = SaveConfigRequest{}
	mi := &file_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveConfigRequest) ProtoMessage() {}

func (x *SaveConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveConfigRequest.ProtoReflect.Descriptor instead.
func (*SaveConfigRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{19}
}

func (x *SaveConfigRequest) GetStaticIp() []byte {
	if x != nil {
		return x.StaticIp
	}
	return nil
}

func (x *SaveConfigRequest) GetStaticGateway() []byte {
	if x != nil {
		return x.StaticGateway
	}
	return nil
}

func (x *SaveConfigRequest) GetStaticSubnet() []byte {
	if x != nil {
		return x.StaticSubnet
	}
	return nil
}

func (x *SaveConfigRequest) GetMdnsHostname() string {
	if x != nil {
		return x.MdnsHostname
	}
	return ""
}

func (x *SaveConfigRequest) GetEnableGatewayCheck() bool {
	if x != nil {
		return x.EnableGatewayCheck
	}
	return false
}

func (x *SaveConfigRequest) GetMacAddress() []byte {
	if x != nil {
		return x.MacAddress
	}
	return nil
}

func (x *SaveConfigRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

type SaveConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveConfigResponse) Reset() {
	*x = SaveConfigResponse{}
	mi := &file_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveConfigResponse) ProtoMessage() {}

func (x *SaveConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveConfigResponse.ProtoReflect.Descriptor instead.
func (*SaveConfigResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{20}
}

type GetStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CalibrationEnabled bool                   `protobuf:"varint,1,opt,name=calibration_enabled,json=calibrationEnabled,proto3" json:"calibration_enabled,omitempty"`
	AttenuationDb      int32                  `protobuf:"varint,2,opt,name=attenuation_db,json=attenuationDb,proto3" json:"attenuation_db,omitempty"`
	ChannelsEnabled    bool                   `protobuf:"varint,3,opt,name=channels_enabled,json=channelsEnabled,proto3" json:"channels_enabled,omitempty"`
	LoFrequencyMhz     int32                  `protobuf:"varint,4,opt,name=lo_frequency_mhz,json=loFrequencyMhz,proto3" json:"lo_frequency_mhz,omitempty"`
	RfSwitch           RfSwitchOption         `protobuf:"varint,5,opt,name=rf_switch,json=rfSwitch,proto3,enum=control.RfSwitchOption" json:"rf_switch,omitempty"`
	MixerSwitch        MixerSwitchOption      `protobuf:"varint,6,opt,name=mixer_switch,json=mixerSwitch,proto3,enum=control.MixerSwitchOption" json:"mixer_switch,omitempty"`
	IfSwitch           IfSwitchOption         `protobuf:"varint,7,opt,name=if_switch,json=ifSwitch,proto3,enum=control.IfSwitchOption" json:"if_switch,omitempty"`
	// Hardware variant: "whalepod", "bc", "straps", or "rf_switch". Used by host
	// tools to suppress fields that aren't physically present (the Whalepod has no
	// switches or PLL, only attenuators).
	BoardType string `protobuf:"bytes,8,opt,name=board_type,json=boardType,proto3" json:"board_type,omitempty"`
	// Currently selected SP8T channel (1..8, or 0 = all-off) on the rf_switch
	// board. Meaningless on other variants.
	RfSwitchChannel int32 `protobuf:"varint,9,opt,name=rf_switch_channel,json=rfSwitchChannel,proto3" json:"rf_switch_channel,omitempty"`
	// Whalepod calibration source: true = internal noise source (CAL_SEL high),
	// false = external (CAL_SEL low). Meaningless on variants without CAL_SEL.
	CalSourceInternal bool `protobuf:"varint,10,opt,name=cal_source_internal,json=calSourceInternal,proto3" json:"cal_source_internal,omitempty"`
	// Whalepod cal-path attenuator setting in dB (the value last written to the
	// CAL_ATT attenuator). Distinct from attenuation_db, which is the frontend
	// attenuator. Meaningless on variants without a cal attenuator.
	CalAttenuationDb int32 `protobuf:"varint,11,opt,name=cal_attenuation_db,json=calAttenuationDb,proto3" json:"cal_attenuation_db,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{21}
}

func (x *GetStatusResponse) GetCalibrationEnabled() bool {
	if x != nil {
		return x.CalibrationEnabled
	}
	return false
}

func (x *GetStatusResponse) GetAttenuationDb() int32 {
	if x != nil {
		return x.AttenuationDb
	}
	return 0
}

func (x *GetStatusResponse) GetChannelsEnabled() bool {
	if x != nil {
		return x.ChannelsEnabled
	}
	return false
}

func (x *GetStatusResponse) GetLoFrequencyMhz() int32 {
	if x != nil {
		return x.LoFrequencyMhz
	}
	return 0
}

func (x *GetStatusResponse) GetRfSwitch() RfSwitchOption {
	if x != nil {
		return x.RfSwitch
	}
	return RfSwitchOption_RF_SWITCH_OPTION_4GHZ_LPF
}

func (x *GetStatusResponse) GetMixerSwitch() MixerSwitchOption {
	if x != nil {
		return x.MixerSwitch
	}
	return MixerSwitchOption_MIXER_SWITCH_OPTION_MIXER
}

func (x *GetStatusResponse) GetIfSwitch() IfSwitchOption {
	if x != nil {
		return x.IfSwitch
	}
	return IfSwitchOption_IF_SWITCH_OPTION_900MHZ_LPF
}

func (x *GetStatusResponse) GetBoardType() string {
	if x != nil {
		return x.BoardType
	}
	return ""
}

func (x *GetStatusResponse) GetRfSwitchChannel() int32 {
	if x != nil {
		return x.RfSwitchChannel
	}
	return 0
}

func (x *GetStatusResponse) GetCalSourceInternal() bool {
	if x != nil {
		return x.CalSourceInternal
	}
	return false
}

func (x *GetStatusResponse) GetCalAttenuationDb() int32 {
	if x != nil {
		return x.CalAttenuationDb
	}
	return 0
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{22}
}

type GetConfigResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StaticIp           []byte                 `protobuf:"bytes,1,opt,name=static_ip,json=staticIp,proto3" json:"static_ip,omitempty"`
	StaticGateway      []byte                 `protobuf:"bytes,2,opt,name=static_gateway,json=staticGateway,proto3" json:"static_gateway,omitempty"`
	StaticSubnet       []byte                 `protobuf:"bytes,3,opt,name=static_subnet,json=staticSubnet,proto3" json:"static_subnet,omitempty"`
	MdnsHostname       string                 `protobuf:"bytes,4,opt,name=mdns_hostname,json=mdnsHostname,proto3" json:"mdns_hostname,omitempty"`
	EnableGatewayCheck bool                   `protobuf:"varint,6,opt,name=enable_gateway_check,json=enableGatewayCheck,proto3" json:"enable_gateway_check,omitempty"`
	SerialNumber       string                 `protobuf:"bytes,7,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	MacAddress         []byte                 `protobuf:"bytes,8,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	FirmwareVersion    string                 `protobuf:"bytes,9,opt,name=firmware_version,json=firmwareVersion,proto3" json:"firmware_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{23}
}

func (x *GetConfigResponse) GetStaticIp() []byte {
	if x != nil {
		return x.StaticIp
	}
	return nil
}

func (x *GetConfigResponse) GetStaticGateway() []byte {
	if x != nil {
		return x.StaticGateway
	}
	return nil
}

func (x *GetConfigResponse) GetStaticSubnet() []byte {
	if x != nil {
		return x.StaticSubnet
	}
	return nil
}

func (x *GetConfigResponse) GetMdnsHostname() string {
	if x != nil {
		return x.MdnsHostname
	}
	return ""
}

func (x *GetConfigResponse) GetEnableGatewayCheck() bool {
	if x != nil {
		return x.EnableGatewayCheck
	}
	return false
}

func (x *GetConfigResponse) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *GetConfigResponse) GetMacAddress() []byte {
	if x != nil {
		return x.MacAddress
	}
	return nil
}

func (x *GetConfigResponse) GetFirmwareVersion() string {
	if x != nil {
		return x.FirmwareVersion
	}
	return ""
}

// EEPROM access (AT24C01D, 128 bytes). address/length are byte offsets into
// the device; data is capped at the device size.
type EepromReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       uint32                 `protobuf:"varint,1,opt,name=address,proto3" json:"address,omitempty"`
	Length        uint32                 `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EepromReadRequest) Reset() {
	*x = EepromReadRequest{}
	mi := &file_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EepromReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EepromReadRequest) ProtoMessage() {}

func (x *EepromReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EepromReadRequest.ProtoReflect.Descriptor instead.
func (*EepromReadRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{24}
}

func (x *EepromReadRequest) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *EepromReadRequest) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type EepromReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       uint32                 `protobuf:"varint,1,opt,name=address,proto3" json:"address,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EepromReadResponse) Reset() {
	*x = EepromReadResponse{}
	mi := &file_control_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EepromReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EepromReadResponse) ProtoMessage() {}

func (x *EepromReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EepromReadResponse.ProtoReflect.Descriptor instead.
func (*EepromReadResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{25}
}

func (x *EepromReadResponse) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *EepromReadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EepromWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       uint32                 `protobuf:"varint,1,opt,name=address,proto3" json:"address,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EepromWriteRequest) Reset() {
	*x = EepromWriteRequest{}
	mi := &file_control_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EepromWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EepromWriteRequest) ProtoMessage() {}

func (x *EepromWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EepromWriteRequest.ProtoReflect.Descriptor instead.
func (*EepromWriteRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{26}
}

func (x *EepromWriteRequest) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *EepromWriteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EepromWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EepromWriteResponse) Reset() {
	*x = EepromWriteResponse{}
	mi := &file_control_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EepromWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EepromWriteResponse) ProtoMessage() {}

func (x *EepromWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EepromWriteResponse.ProtoReflect.Descriptor instead.
func (*EepromWriteResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{27}
}

func (x *EepromWriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Generic error reply. Sent when the firmware cannot handle a request at all —
// e.g. an unknown/unsupported message id, or a packet that failed to decode —
// so the host gets a definite answer instead of blocking until it times out.
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=control.ErrorCode" json:"code,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"` // short human-readable context; may be empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_control_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{28}
}

func (x *ErrorResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ErrorResponse) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// Packet message with all request and response types
type Packet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageId:
	//
	//	*Packet_SetCalEnabledRequest
	//	*Packet_SetCalEnabledResponse
	//	*Packet_SetFrontendAttenuationRequest
	//	*Packet_SetChannelsEnabledRequest
	//	*Packet_SetFrontendAttenuationResponse
	//	*Packet_SetChannelsEnabledResponse
	//	*Packet_GetStatusRequest
	//	*Packet_GetStatusResponse
	//	*Packet_SetSwitchesRequest
	//	*Packet_SetSwitchesResponse
	//	*Packet_SetPllFrequencyRequest
	//	*Packet_SetPllFrequencyResponse
	//	*Packet_SetRfBandRequest
	//	*Packet_SetRfBandResponse
	//	*Packet_SetCalAttenuationRequest
	//	*Packet_SetCalAttenuationResponse
	//	*Packet_SaveConfigRequest
	//	*Packet_SaveConfigResponse
	//	*Packet_GetConfigRequest
	//	*Packet_GetConfigResponse
	//	*Packet_EepromReadRequest
	//	*Packet_EepromReadResponse
	//	*Packet_EepromWriteRequest
	//	*Packet_EepromWriteResponse
	//	*Packet_SetRfSwitchChannelRequest
	//	*Packet_SetRfSwitchChannelResponse
	//	*Packet_SetCalSourceRequest
	//	*Packet_SetCalSourceResponse
	//	*Packet_ErrorResponse
	MessageId     isPacket_MessageId `protobuf_oneof:"message_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_control_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{29}
}

func (x *Packet) GetMessageId() isPacket_MessageId {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *Packet) GetSetCalEnabledRequest() *SetCalibrationEnabledRequest {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SetCalEnabledRequest); ok {
			return x.SetCalEnabledRequest
		}
	}
	return nil
}

func (x *Packet) GetSetCalEnabledResponse() *SetCalibrationEnabledResponse {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SetCalEnabledResponse); ok {
			return x.SetCalEnabledResponse
		}
	}
	return nil
}

func (x *Packet) GetSetFrontendAttenuationRequest() *SetAttenuationRequest {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SetFrontendAttenuationRequest); ok {
			return x.SetFrontendAttenuationRequest
		}
	}
	return nil
}

func (x *Packet) GetSetChannelsEnabledRequest() *SetChannelsEnabledRequest {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SetChannelsEnabledRequest); ok {
			return x.SetChannelsEnabledRequest
		}
	}
	return nil
}

func (x *Packet) GetSetFrontendAttenuationResponse() *SetFrontendAttenuationResponse {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SetFrontendAttenuationResponse); ok {
			return x.SetFrontendAttenuationResponse
		}
	}
	return nil
}

func (x *Packet) GetSetChannelsEnabledResponse() *SetChannelsEnabledResponse {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SetChannelsEnabledResponse); ok {
			return x.SetChannelsEnabledResponse
		}
	}
	return nil
}

func (x *Packet) GetGetStatusRequest() *GetStatusRequest {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_GetStatusRequest); ok {
			return x.GetStatusRequest
		}
	}
	return nil
}

func (x *Packet) GetGetStatusResponse() *GetStatusResponse {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_GetStatusResponse); ok {
			return x.GetStatusResponse
		}
	}
	return nil
}

func (x *Packet) GetSetSwitchesRequest() *SetSwitchesRequest {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SetSwitchesRequest); ok {
			return x.SetSwitchesRequest
		}
	}
	return nil
}

func (x *Packet) GetSetSwitchesResponse() *SetSwitchesResponse {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SetSwitchesResponse); ok {
			return x.SetSwitchesResponse
		}
	}
	return nil
}

func (x *Packet) GetSetPllFrequencyRequest() *SetPllFrequencyRequest {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SetPllFrequencyRequest); ok {
			return x.SetPllFrequencyRequest
		}
	}
	return nil
}

func (x *Packet) GetSetPllFrequencyResponse() *SetPllFrequencyResponse {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SetPllFrequencyResponse); ok {
			return x.SetPllFrequencyResponse
		}
	}
	return nil
}

func (x *Packet) GetSetRfBandRequest() *SetRfBandRequest {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SetRfBandRequest); ok {
			return x.SetRfBandRequest
		}
	}
	return nil
}

func (x *Packet) GetSetRfBandResponse() *SetRfBandResponse {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SetRfBandResponse); ok {
			return x.SetRfBandResponse
		}
	}
	return nil
}

func (x *Packet) GetSetCalAttenuationRequest() *SetAttenuationRequest {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SetCalAttenuationRequest); ok {
			return x.SetCalAttenuationRequest
		}
	}
	return nil
}

func (x *Packet) GetSetCalAttenuationResponse() *SetCalAttenuationResponse {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SetCalAttenuationResponse); ok {
			return x.SetCalAttenuationResponse
		}
	}
	return nil
}

func (x *Packet) GetSaveConfigRequest() *SaveConfigRequest {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SaveConfigRequest); ok {
			return x.SaveConfigRequest
		}
	}
	return nil
}

func (x *Packet) GetSaveConfigResponse() *SaveConfigResponse {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SaveConfigResponse); ok {
			return x.SaveConfigResponse
		}
	}
	return nil
}

func (x *Packet) GetGetConfigRequest() *GetConfigRequest {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_GetConfigRequest); ok {
			return x.GetConfigRequest
		}
	}
	return nil
}

func (x *Packet) GetGetConfigResponse() *GetConfigResponse {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_GetConfigResponse); ok {
			return x.GetConfigResponse
		}
	}
	return nil
}

func (x *Packet) GetEepromReadRequest() *EepromReadRequest {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_EepromReadRequest); ok {
			return x.EepromReadRequest
		}
	}
	return nil
}

func (x *Packet) GetEepromReadResponse() *EepromReadResponse {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_EepromReadResponse); ok {
			return x.EepromReadResponse
		}
	}
	return nil
}

func (x *Packet) GetEepromWriteRequest() *EepromWriteRequest {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_EepromWriteRequest); ok {
			return x.EepromWriteRequest
		}
	}
	return nil
}

func (x *Packet) GetEepromWriteResponse() *EepromWriteResponse {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_EepromWriteResponse); ok {
			return x.EepromWriteResponse
		}
	}
	return nil
}

func (x *Packet) GetSetRfSwitchChannelRequest() *SetRfSwitchChannelRequest {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SetRfSwitchChannelRequest); ok {
			return x.SetRfSwitchChannelRequest
		}
	}
	return nil
}

func (x *Packet) GetSetRfSwitchChannelResponse() *SetRfSwitchChannelResponse {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SetRfSwitchChannelResponse); ok {
			return x.SetRfSwitchChannelResponse
		}
	}
	return nil
}

func (x *Packet) GetSetCalSourceRequest() *SetCalSourceRequest {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SetCalSourceRequest); ok {
			return x.SetCalSourceRequest
		}
	}
	return nil
}

func (x *Packet) GetSetCalSourceResponse() *SetCalSourceResponse {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_SetCalSourceResponse); ok {
			return x.SetCalSourceResponse
		}
	}
	return nil
}

func (x *Packet) GetErrorResponse() *ErrorResponse {
	if x != nil {
		if x, ok := x.MessageId.(*Packet_ErrorResponse); ok {
			return x.ErrorResponse
		}
	}
	return nil
}

type isPacket_MessageId interface {
	isPacket_MessageId()
}

type Packet_SetCalEnabledRequest struct {
	SetCalEnabledRequest *SetCalibrationEnabledRequest `protobuf:"bytes,1,opt,name=set_cal_enabled_request,json=setCalEnabledRequest,proto3,oneof"`
}

type Packet_SetCalEnabledResponse struct {
	SetCalEnabledResponse *SetCalibrationEnabledResponse `protobuf:"bytes,2,opt,name=set_cal_enabled_response,json=setCalEnabledResponse,proto3,oneof"`
}

type Packet_SetFrontendAttenuationRequest struct {
	SetFrontendAttenuationRequest *SetAttenuationRequest `protobuf:"bytes,3,opt,name=set_frontend_attenuation_request,json=setFrontendAttenuationRequest,proto3,oneof"`
}

type Packet_SetChannelsEnabledRequest struct {
	SetChannelsEnabledRequest *SetChannelsEnabledRequest `protobuf:"bytes,4,opt,name=set_channels_enabled_request,json=setChannelsEnabledRequest,proto3,oneof"`
}

type Packet_SetFrontendAttenuationResponse struct {
	SetFrontendAttenuationResponse *SetFrontendAttenuationResponse `protobuf:"bytes,5,opt,name=set_frontend_attenuation_response,json=setFrontendAttenuationResponse,proto3,oneof"`
}

type Packet_SetChannelsEnabledResponse struct {
	SetChannelsEnabledResponse *SetChannelsEnabledResponse `protobuf:"bytes,6,opt,name=set_channels_enabled_response,json=setChannelsEnabledResponse,proto3,oneof"`
}

type Packet_GetStatusRequest struct {
	GetStatusRequest *GetStatusRequest `protobuf:"bytes,7,opt,name=get_status_request,json=getStatusRequest,proto3,oneof"`
}

type Packet_GetStatusResponse struct {
	GetStatusResponse *GetStatusResponse `protobuf:"bytes,8,opt,name=get_status_response,json=getStatusResponse,proto3,oneof"`
}

type Packet_SetSwitchesRequest struct {
	SetSwitchesRequest *SetSwitchesRequest `protobuf:"bytes,9,opt,name=set_switches_request,json=setSwitchesRequest,proto3,oneof"`
}

type Packet_SetSwitchesResponse struct {
	SetSwitchesResponse *SetSwitchesResponse `protobuf:"bytes,10,opt,name=set_switches_response,json=setSwitchesResponse,proto3,oneof"`
}

type Packet_SetPllFrequencyRequest struct {
	SetPllFrequencyRequest *SetPllFrequencyRequest `protobuf:"bytes,11,opt,name=set_pll_frequency_request,json=setPllFrequencyRequest,proto3,oneof"`
}

type Packet_SetPllFrequencyResponse struct {
	SetPllFrequencyResponse *SetPllFrequencyResponse `protobuf:"bytes,12,opt,name=set_pll_frequency_response,json=setPllFrequencyResponse,proto3,oneof"`
}

type Packet_SetRfBandRequest struct {
	SetRfBandRequest *SetRfBandRequest `protobuf:"bytes,13,opt,name=set_rf_band_request,json=setRfBandRequest,proto3,oneof"`
}

type Packet_SetRfBandResponse struct {
	SetRfBandResponse *SetRfBandResponse `protobuf:"bytes,14,opt,name=set_rf_band_response,json=setRfBandResponse,proto3,oneof"`
}

type Packet_SetCalAttenuationRequest struct {
	SetCalAttenuationRequest *SetAttenuationRequest `protobuf:"bytes,15,opt,name=set_cal_attenuation_request,json=setCalAttenuationRequest,proto3,oneof"`
}

type Packet_SetCalAttenuationResponse struct {
	SetCalAttenuationResponse *SetCalAttenuationResponse `protobuf:"bytes,16,opt,name=set_cal_attenuation_response,json=setCalAttenuationResponse,proto3,oneof"`
}

type Packet_SaveConfigRequest struct {
	SaveConfigRequest *SaveConfigRequest `protobuf:"bytes,17,opt,name=save_config_request,json=saveConfigRequest,proto3,oneof"`
}

type Packet_SaveConfigResponse struct {
	SaveConfigResponse *SaveConfigResponse `protobuf:"bytes,18,opt,name=save_config_response,json=saveConfigResponse,proto3,oneof"`
}

type Packet_GetConfigRequest struct {
	GetConfigRequest *GetConfigRequest `protobuf:"bytes,19,opt,name=get_config_request,json=getConfigRequest,proto3,oneof"`
}

type Packet_GetConfigResponse struct {
	GetConfigResponse *GetConfigResponse `protobuf:"bytes,20,opt,name=get_config_response,json=getConfigResponse,proto3,oneof"`
}

type Packet_EepromReadRequest struct {
	EepromReadRequest *EepromReadRequest `protobuf:"bytes,21,opt,name=eeprom_read_request,json=eepromReadRequest,proto3,oneof"`
}

type Packet_EepromReadResponse struct {
	EepromReadResponse *EepromReadResponse `protobuf:"bytes,22,opt,name=eeprom_read_response,json=eepromReadResponse,proto3,oneof"`
}

type Packet_EepromWriteRequest struct {
	EepromWriteRequest *EepromWriteRequest `protobuf:"bytes,23,opt,name=eeprom_write_request,json=eepromWriteRequest,proto3,oneof"`
}

type Packet_EepromWriteResponse struct {
	EepromWriteResponse *EepromWriteResponse `protobuf:"bytes,24,opt,name=eeprom_write_response,json=eepromWriteResponse,proto3,oneof"`
}

type Packet_SetRfSwitchChannelRequest struct {
	SetRfSwitchChannelRequest *SetRfSwitchChannelRequest `protobuf:"bytes,25,opt,name=set_rf_switch_channel_request,json=setRfSwitchChannelRequest,proto3,oneof"`
}

type Packet_SetRfSwitchChannelResponse struct {
	SetRfSwitchChannelResponse *SetRfSwitchChannelResponse `protobuf:"bytes,26,opt,name=set_rf_switch_channel_response,json=setRfSwitchChannelResponse,proto3,oneof"`
}

type Packet_SetCalSourceRequest struct {
	SetCalSourceRequest *SetCalSourceRequest `protobuf:"bytes,27,opt,name=set_cal_source_request,json=setCalSourceRequest,proto3,oneof"`
}

type Packet_SetCalSourceResponse struct {
	SetCalSourceResponse *SetCalSourceResponse `protobuf:"bytes,28,opt,name=set_cal_source_response,json=setCalSourceResponse,proto3,oneof"`
}

type Packet_ErrorResponse struct {
	ErrorResponse *ErrorResponse `protobuf:"bytes,29,opt,name=error_response,json=errorResponse,proto3,oneof"`
}

func (*Packet_SetCalEnabledRequest) isPacket_MessageId() {}

func (*Packet_SetCalEnabledResponse) isPacket_MessageId() {}

func (*Packet_SetFrontendAttenuationRequest) isPacket_MessageId() {}

func (*Packet_SetChannelsEnabledRequest) isPacket_MessageId() {}

func (*Packet_SetFrontendAttenuationResponse) isPacket_MessageId() {}

func (*Packet_SetChannelsEnabledResponse) isPacket_MessageId() {}

func (*Packet_GetStatusRequest) isPacket_MessageId() {}

func (*Packet_GetStatusResponse) isPacket_MessageId() {}

func (*Packet_SetSwitchesRequest) isPacket_MessageId() {}

func (*Packet_SetSwitchesResponse) isPacket_MessageId() {}

func (*Packet_SetPllFrequencyRequest) isPacket_MessageId() {}

func (*Packet_SetPllFrequencyResponse) isPacket_MessageId() {}

func (*Packet_SetRfBandRequest) isPacket_MessageId() {}

func (*Packet_SetRfBandResponse) isPacket_MessageId() {}

func (*Packet_SetCalAttenuationRequest) isPacket_MessageId() {}

func (*Packet_SetCalAttenuationResponse) isPacket_MessageId() {}

func (*Packet_SaveConfigRequest) isPacket_MessageId() {}

func (*Packet_SaveConfigResponse) isPacket_MessageId() {}

func (*Packet_GetConfigRequest) isPacket_MessageId() {}

func (*Packet_GetConfigResponse) isPacket_MessageId() {}

func (*Packet_EepromReadRequest) isPacket_MessageId() {}

func (*Packet_EepromReadResponse) isPacket_MessageId() {}

func (*Packet_EepromWriteRequest) isPacket_MessageId() {}

func (*Packet_EepromWriteResponse) isPacket_MessageId() {}

func (*Packet_SetRfSwitchChannelRequest) isPacket_MessageId() {}

func (*Packet_SetRfSwitchChannelResponse) isPacket_MessageId() {}

func (*Packet_SetCalSourceRequest) isPacket_MessageId() {}

func (*Packet_SetCalSourceResponse) isPacket_MessageId() {}

func (*Packet_ErrorResponse) isPacket_MessageId() {}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\acontrol\"=\n" +
	"\x16SetPllFrequencyRequest\x12#\n" +
	"\rfrequency_mhz\x18\x01 \x01(\x05R\ffrequencyMhz\"7\n" +
	"\x10SetRfBandRequest\x12#\n" +
	"\x04band\x18\x01 \x01(\x0e2\x0f.control.RfBandR\x04band\"\xbf\x01\n" +
	"\x12SetSwitchesRequest\x124\n" +
	"\trf_switch\x18\x01 \x01(\x0e2\x17.control.RfSwitchOptionR\brfSwitch\x12=\n" +
	"\fmixer_switch\x18\x02 \x01(\x0e2\x1a.control.MixerSwitchOptionR\vmixerSwitch\x124\n" +
	"\tif_switch\x18\x03 \x01(\x0e2\x17.control.IfSwitchOptionR\bifSwitch\"8\n" +
	"\x1cSetCalibrationEnabledRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"1\n" +
	"\x13SetCalSourceRequest\x12\x1a\n" +
	"\binternal\x18\x01 \x01(\bR\binternal\"5\n" +
	"\x19SetChannelsEnabledRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\">\n" +
	"\x15SetAttenuationRequest\x12%\n" +
	"\x0eattenuation_db\x18\x01 \x01(\x05R\rattenuationDb\"5\n" +
	"\x19SetRfSwitchChannelRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\x05R\achannel\"\x1f\n" +
	"\x1dSetCalibrationEnabledResponse\"\x16\n" +
	"\x14SetCalSourceResponse\"\x18\n" +
	"\x16SetAttenuationResponse\"\x1c\n" +
	"\x1aSetChannelsEnabledResponse\"\x15\n" +
	"\x13SetSwitchesResponse\"\x19\n" +
	"\x17SetPllFrequencyResponse\"\x13\n" +
	"\x11SetRfBandResponse\"\x1c\n" +
	"\x1aSetRfSwitchChannelResponse\"\x12\n" +
	"\x10GetStatusRequest\"\x1b\n" +
	"\x19SetCalAttenuationResponse\" \n" +
	"\x1eSetFrontendAttenuationResponse\"\x99\x02\n" +
	"\x11SaveConfigRequest\x12\x1b\n" +
	"\tstatic_ip\x18\x01 \x01(\fR\bstaticIp\x12%\n" +
	"\x0estatic_gateway\x18\x02 \x01(\fR\rstaticGateway\x12#\n" +
	"\rstatic_subnet\x18\x03 \x01(\fR\fstaticSubnet\x12#\n" +
	"\rmdns_hostname\x18\x04 \x01(\tR\fmdnsHostname\x120\n" +
	"\x14enable_gateway_check\x18\x06 \x01(\bR\x12enableGatewayCheck\x12\x1f\n" +
	"\vmac_address\x18\a \x01(\fR\n" +
	"macAddress\x12#\n" +
	"\rserial_number\x18\b \x01(\tR\fserialNumber\"\x14\n" +
	"\x12SaveConfigResponse\"\x94\x04\n" +
	"\x11GetStatusResponse\x12/\n" +
	"\x13calibration_enabled\x18\x01 \x01(\bR\x12calibrationEnabled\x12%\n" +
	"\x0eattenuation_db\x18\x02 \x01(\x05R\rattenuationDb\x12)\n" +
	"\x10channels_enabled\x18\x03 \x01(\bR\x0fchannelsEnabled\x12(\n" +
	"\x10lo_frequency_mhz\x18\x04 \x01(\x05R\x0eloFrequencyMhz\x124\n" +
	"\trf_switch\x18\x05 \x01(\x0e2\x17.control.RfSwitchOptionR\brfSwitch\x12=\n" +
	"\fmixer_switch\x18\x06 \x01(\x0e2\x1a.control.MixerSwitchOptionR\vmixerSwitch\x124\n" +
	"\tif_switch\x18\a \x01(\x0e2\x17.control.IfSwitchOptionR\bifSwitch\x12\x1d\n" +
	"\n" +
	"board_type\x18\b \x01(\tR\tboardType\x12*\n" +
	"\x11rf_switch_channel\x18\t \x01(\x05R\x0frfSwitchChannel\x12.\n" +
	"\x13cal_source_internal\x18\n" +
	" \x01(\bR\x11calSourceInternal\x12,\n" +
	"\x12cal_attenuation_db\x18\v \x01(\x05R\x10calAttenuationDb\"\x12\n" +
	"\x10GetConfigRequest\"\xc4\x02\n" +
	"\x11GetConfigResponse\x12\x1b\n" +
	"\tstatic_ip\x18\x01 \x01(\fR\bstaticIp\x12%\n" +
	"\x0estatic_gateway\x18\x02 \x01(\fR\rstaticGateway\x12#\n" +
	"\rstatic_subnet\x18\x03 \x01(\fR\fstaticSubnet\x12#\n" +
	"\rmdns_hostname\x18\x04 \x01(\tR\fmdnsHostname\x120\n" +
	"\x14enable_gateway_check\x18\x06 \x01(\bR\x12enableGatewayCheck\x12#\n" +
	"\rserial_number\x18\a \x01(\tR\fserialNumber\x12\x1f\n" +
	"\vmac_address\x18\b \x01(\fR\n" +
	"macAddress\x12)\n" +
	"\x10firmware_version\x18\t \x01(\tR\x0ffirmwareVersion\"E\n" +
	"\x11EepromReadRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\rR\aaddress\x12\x16\n" +
	"\x06length\x18\x02 \x01(\rR\x06length\"B\n" +
	"\x12EepromReadResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\rR\aaddress\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"B\n" +
	"\x12EepromWriteRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\rR\aaddress\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"/\n" +
	"\x13EepromWriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"O\n" +
	"\rErrorResponse\x12&\n" +
	"\x04code\x18\x01 \x01(\x0e2\x12.control.ErrorCodeR\x04code\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\"\xa8\x14\n" +
	"\x06Packet\x12^\n" +
	"\x17set_cal_enabled_request\x18\x01 \x01(\v2%.control.SetCalibrationEnabledRequestH\x00R\x14setCalEnabledRequest\x12a\n" +
	"\x18set_cal_enabled_response\x18\x02 \x01(\v2&.control.SetCalibrationEnabledResponseH\x00R\x15setCalEnabledResponse\x12i\n" +
	" set_frontend_attenuation_request\x18\x03 \x01(\v2\x1e.control.SetAttenuationRequestH\x00R\x1dsetFrontendAttenuationRequest\x12e\n" +
	"\x1cset_channels_enabled_request\x18\x04 \x01(\v2\".control.SetChannelsEnabledRequestH\x00R\x19setChannelsEnabledRequest\x12t\n" +
	"!set_frontend_attenuation_response\x18\x05 \x01(\v2'.control.SetFrontendAttenuationResponseH\x00R\x1esetFrontendAttenuationResponse\x12h\n" +
	"\x1dset_channels_enabled_response\x18\x06 \x01(\v2#.control.SetChannelsEnabledResponseH\x00R\x1asetChannelsEnabledResponse\x12I\n" +
	"\x12get_status_request\x18\a \x01(\v2\x19.control.GetStatusRequestH\x00R\x10getStatusRequest\x12L\n" +
	"\x13get_status_response\x18\b \x01(\v2\x1a.control.GetStatusResponseH\x00R\x11getStatusResponse\x12O\n" +
	"\x14set_switches_request\x18\t \x01(\v2\x1b.control.SetSwitchesRequestH\x00R\x12setSwitchesRequest\x12R\n" +
	"\x15set_switches_response\x18\n" +
	" \x01(\v2\x1c.control.SetSwitchesResponseH\x00R\x13setSwitchesResponse\x12\\\n" +
	"\x19set_pll_frequency_request\x18\v \x01(\v2\x1f.control.SetPllFrequencyRequestH\x00R\x16setPllFrequencyRequest\x12_\n" +
	"\x1aset_pll_frequency_response\x18\f \x01(\v2 .control.SetPllFrequencyResponseH\x00R\x17setPllFrequencyResponse\x12J\n" +
	"\x13set_rf_band_request\x18\r \x01(\v2\x19.control.SetRfBandRequestH\x00R\x10setRfBandRequest\x12M\n" +
	"\x14set_rf_band_response\x18\x0e \x01(\v2\x1a.control.SetRfBandResponseH\x00R\x11setRfBandResponse\x12_\n" +
	"\x1bset_cal_attenuation_request\x18\x0f \x01(\v2\x1e.control.SetAttenuationRequestH\x00R\x18setCalAttenuationRequest\x12e\n" +
	"\x1cset_cal_attenuation_response\x18\x10 \x01(\v2\".control.SetCalAttenuationResponseH\x00R\x19setCalAttenuationResponse\x12L\n" +
	"\x13save_config_request\x18\x11 \x01(\v2\x1a.control.SaveConfigRequestH\x00R\x11saveConfigRequest\x12O\n" +
	"\x14save_config_response\x18\x12 \x01(\v2\x1b.control.SaveConfigResponseH\x00R\x12saveConfigResponse\x12I\n" +
	"\x12get_config_request\x18\x13 \x01(\v2\x19.control.GetConfigRequestH\x00R\x10getConfigRequest\x12L\n" +
	"\x13get_config_response\x18\x14 \x01(\v2\x1a.control.GetConfigResponseH\x00R\x11getConfigResponse\x12L\n" +
	"\x13eeprom_read_request\x18\x15 \x01(\v2\x1a.control.EepromReadRequestH\x00R\x11eepromReadRequest\x12O\n" +
	"\x14eeprom_read_response\x18\x16 \x01(\v2\x1b.control.EepromReadResponseH\x00R\x12eepromReadResponse\x12O\n" +
	"\x14eeprom_write_request\x18\x17 \x01(\v2\x1b.control.EepromWriteRequestH\x00R\x12eepromWriteRequest\x12R\n" +
	"\x15eeprom_write_response\x18\x18 \x01(\v2\x1c.control.EepromWriteResponseH\x00R\x13eepromWriteResponse\x12f\n" +
	"\x1dset_rf_switch_channel_request\x18\x19 \x01(\v2\".control.SetRfSwitchChannelRequestH\x00R\x19setRfSwitchChannelRequest\x12i\n" +
	"\x1eset_rf_switch_channel_response\x18\x1a \x01(\v2#.control.SetRfSwitchChannelResponseH\x00R\x1asetRfSwitchChannelResponse\x12S\n" +
	"\x16set_cal_source_request\x18\x1b \x01(\v2\x1c.control.SetCalSourceRequestH\x00R\x13setCalSourceRequest\x12V\n" +
	"\x17set_cal_source_response\x18\x1c \x01(\v2\x1d.control.SetCalSourceResponseH\x00R\x14setCalSourceResponse\x12?\n" +
	"\x0eerror_response\x18\x1d \x01(\v2\x16.control.ErrorResponseH\x00R\rerrorResponseB\f\n" +
	"\n" +
	"message_id*N\n" +
	"\x0eRfSwitchOption\x12\x1d\n" +
	"\x19RF_SWITCH_OPTION_4GHZ_LPF\x10\x00\x12\x1d\n" +
	"\x19RF_SWITCH_OPTION_2GHZ_LPF\x10\x01*R\n" +
	"\x11MixerSwitchOption\x12\x1d\n" +
	"\x19MIXER_SWITCH_OPTION_MIXER\x10\x00\x12\x1e\n" +
	"\x1aMIXER_SWITCH_OPTION_BYPASS\x10\x01*W\n" +
	"\x0eIfSwitchOption\x12\x1f\n" +
	"\x1bIF_SWITCH_OPTION_900MHZ_LPF\x10\x00\x12$\n" +
	" IF_SWITCH_OPTION_1_2GHZ_BANDPASS\x10\x01*\x86\x01\n" +
	"\x06RfBand\x12\x15\n" +
	"\x11RF_BAND_10_900MHZ\x10\x00\x12\x17\n" +
	"\x13RF_BAND_900_1800MHZ\x10\x01\x12\x18\n" +
	"\x14RF_BAND_1800_2700MHZ\x10\x02\x12\x18\n" +
	"\x14RF_BAND_2700_3600MHZ\x10\x03\x12\x18\n" +
	"\x14RF_BAND_3600_4500MHZ\x10\x04*\xa0\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ERROR_CODE_UNSUPPORTED\x10\x01\x12\x1c\n" +
	"\x18ERROR_CODE_DECODE_FAILED\x10\x02\x12\x1e\n" +
	"\x1aERROR_CODE_INVALID_REQUEST\x10\x03\x12\x1d\n" +
	"\x19ERROR_CODE_HARDWARE_ERROR\x10\x04B7Z5github.com/OcupointInc/rf-control/controlpb;controlpbb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_control_proto_goTypes = []any{
	(RfSwitchOption)(0),                    // 0: control.RfSwitchOption
	(MixerSwitchOption)(0),                 // 1: control.MixerSwitchOption
	(IfSwitchOption)(0),                    // 2: control.IfSwitchOption
	(RfBand)(0),                            // 3: control.RfBand
	(ErrorCode)(0),                         // 4: control.ErrorCode
	(*SetPllFrequencyRequest)(nil),         // 5: control.SetPllFrequencyRequest
	(*SetRfBandRequest)(nil),               // 6: control.SetRfBandRequest
	(*SetSwitchesRequest)(nil),             // 7: control.SetSwitchesRequest
	(*SetCalibrationEnabledRequest)(nil),   // 8: control.SetCalibrationEnabledRequest
	(*SetCalSourceRequest)(nil),            // 9: control.SetCalSourceRequest
	(*SetChannelsEnabledRequest)(nil),      // 10: control.SetChannelsEnabledRequest
	(*SetAttenuationRequest)(nil),          // 11: control.SetAttenuationRequest
	(*SetRfSwitchChannelRequest)(nil),      // 12: control.SetRfSwitchChannelRequest
	(*SetCalibrationEnabledResponse)(nil),  // 13: control.SetCalibrationEnabledResponse
	(*SetCalSourceResponse)(nil),           // 14: control.SetCalSourceResponse
	(*SetAttenuationResponse)(nil),         // 15: control.SetAttenuationResponse
	(*SetChannelsEnabledResponse)(nil),     // 16: control.SetChannelsEnabledResponse
	(*SetSwitchesResponse)(nil),            // 17: control.SetSwitchesResponse
	(*SetPllFrequencyResponse)(nil),        // 18: control.SetPllFrequencyResponse
	(*SetRfBandResponse)(nil),              // 19: control.SetRfBandResponse
	(*SetRfSwitchChannelResponse)(nil),     // 20: control.SetRfSwitchChannelResponse
	(*GetStatusRequest)(nil),               // 21: control.GetStatusRequest
	(*SetCalAttenuationResponse)(nil),      // 22: control.SetCalAttenuationResponse
	(*SetFrontendAttenuationResponse)(nil), // 23: control.SetFrontendAttenuationResponse
	(*SaveConfigRequest)(nil),              // 24: control.SaveConfigRequest
	(*SaveConfigResponse)(nil),             // 25: control.SaveConfigResponse
	(*GetStatusResponse)(nil),              // 26: control.GetStatusResponse
	(*GetConfigRequest)(nil),               // 27: control.GetConfigRequest
	(*GetConfigResponse)(nil),              // 28: control.GetConfigResponse
	(*EepromReadRequest)(nil),              // 29: control.EepromReadRequest
	(*EepromReadResponse)(nil),             // 30: control.EepromReadResponse
	(*EepromWriteRequest)(nil),             // 31: control.EepromWriteRequest
	(*EepromWriteResponse)(nil),            // 32: control.EepromWriteResponse
	(*ErrorResponse)(nil),                  // 33: control.ErrorResponse
	(*Packet)(nil),                         // 34: control.Packet
}
var file_control_proto_depIdxs = []int32{
	3,  // 0: control.SetRfBandRequest.band:type_name -> control.RfBand
	0,  // 1: control.SetSwitchesRequest.rf_switch:type_name -> control.RfSwitchOption
	1,  // 2: control.SetSwitchesRequest.mixer_switch:type_name -> control.MixerSwitchOption
	2,  // 3: control.SetSwitchesRequest.if_switch:type_name -> control.IfSwitchOption
	0,  // 4: control.GetStatusResponse.rf_switch:type_name -> control.RfSwitchOption
	1,  // 5: control.GetStatusResponse.mixer_switch:type_name -> control.MixerSwitchOption
	2,  // 6: control.GetStatusResponse.if_switch:type_name -> control.IfSwitchOption
	4,  // 7: control.ErrorResponse.code:type_name -> control.ErrorCode
	8,  // 8: control.Packet.set_cal_enabled_request:type_name -> control.SetCalibrationEnabledRequest
	13, // 9: control.Packet.set_cal_enabled_response:type_name -> control.SetCalibrationEnabledResponse
	11, // 10: control.Packet.set_frontend_attenuation_request:type_name -> control.SetAttenuationRequest
	10, // 11: control.Packet.set_channels_enabled_request:type_name -> control.SetChannelsEnabledRequest
	23, // 12: control.Packet.set_frontend_attenuation_response:type_name -> control.SetFrontendAttenuationResponse
	16, // 13: control.Packet.set_channels_enabled_response:type_name -> control.SetChannelsEnabledResponse
	21, // 14: control.Packet.get_status_request:type_name -> control.GetStatusRequest
	26, // 15: control.Packet.get_status_response:type_name -> control.GetStatusResponse
	7,  // 16: control.Packet.set_switches_request:type_name -> control.SetSwitchesRequest
	17, // 17: control.Packet.set_switches_response:type_name -> control.SetSwitchesResponse
	5,  // 18: control.Packet.set_pll_frequency_request:type_name -> control.SetPllFrequencyRequest
	18, // 19: control.Packet.set_pll_frequency_response:type_name -> control.SetPllFrequencyResponse
	6,  // 20: control.Packet.set_rf_band_request:type_name -> control.SetRfBandRequest
	19, // 21: control.Packet.set_rf_band_response:type_name -> control.SetRfBandResponse
	11, // 22: control.Packet.set_cal_attenuation_request:type_name -> control.SetAttenuationRequest
	22, // 23: control.Packet.set_cal_attenuation_response:type_name -> control.SetCalAttenuationResponse
	24, // 24: control.Packet.save_config_request:type_name -> control.SaveConfigRequest
	25, // 25: control.Packet.save_config_response:type_name -> control.SaveConfigResponse
	27, // 26: control.Packet.get_config_request:type_name -> control.GetConfigRequest
	28, // 27: control.Packet.get_config_response:type_name -> control.GetConfigResponse
	29, // 28: control.Packet.eeprom_read_request:type_name -> control.EepromReadRequest
	30, // 29: control.Packet.eeprom_read_response:type_name -> control.EepromReadResponse
	31, // 30: control.Packet.eeprom_write_request:type_name -> control.EepromWriteRequest
	32, // 31: control.Packet.eeprom_write_response:type_name -> control.EepromWriteResponse
	12, // 32: control.Packet.set_rf_switch_channel_request:type_name -> control.SetRfSwitchChannelRequest
	20, // 33: control.Packet.set_rf_switch_channel_response:type_name -> control.SetRfSwitchChannelResponse
	9,  // 34: control.Packet.set_cal_source_request:type_name -> control.SetCalSourceRequest
	14, // 35: control.Packet.set_cal_source_response:type_name -> control.SetCalSourceResponse
	33, // 36: control.Packet.error_response:type_name -> control.ErrorResponse
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_control_proto_msgTypes[29].OneofWrappers = []any{
		(*Packet_SetCalEnabledRequest)(nil),
		(*Packet_SetCalEnabledResponse)(nil),
		(*Packet_SetFrontendAttenuationRequest)(nil),
		(*Packet_SetChannelsEnabledRequest)(nil),
		(*Packet_SetFrontendAttenuationResponse)(nil),
		(*Packet_SetChannelsEnabledResponse)(nil),
		(*Packet_GetStatusRequest)(nil),
		(*Packet_GetStatusResponse)(nil),
		(*Packet_SetSwitchesRequest)(nil),
		(*Packet_SetSwitchesResponse)(nil),
		(*Packet_SetPllFrequencyRequest)(nil),
		(*Packet_SetPllFrequencyResponse)(nil),
		(*Packet_SetRfBandRequest)(nil),
		(*Packet_SetRfBandResponse)(nil),
		(*Packet_SetCalAttenuationRequest)(nil),
		(*Packet_SetCalAttenuationResponse)(nil),
		(*Packet_SaveConfigRequest)(nil),
		(*Packet_SaveConfigResponse)(nil),
		(*Packet_GetConfigRequest)(nil),
		(*Packet_GetConfigResponse)(nil),
		(*Packet_EepromReadRequest)(nil),
		(*Packet_EepromReadResponse)(nil),
		(*Packet_EepromWriteRequest)(nil),
		(*Packet_EepromWriteResponse)(nil),
		(*Packet_SetRfSwitchChannelRequest)(nil),
		(*Packet_SetRfSwitchChannelResponse)(nil),
		(*Packet_SetCalSourceRequest)(nil),
		(*Packet_SetCalSourceResponse)(nil),
		(*Packet_ErrorResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		EnumInfos:         file_control_proto_enumTypes,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
