// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function ConfigureCW(arg1:gui.CWRequest):Promise<gui.DeviceSnapshot>;

export function ConfigureSweep(arg1:gui.SweepRequest):Promise<gui.DeviceSnapshot>;

export function Connect(arg1:gui.Endpoint):Promise<gui.DeviceSnapshot>;

export function Disconnect():Promise<void>;

export function Discover():Promise<gui.DiscoveryResult>;

export function GetStatus():Promise<gui.DeviceSnapshot>;

export function LoadTuningProfile():Promise<gui.TuningProfile>;

export function PreviewNetwork(arg1:string):Promise<gui.NetworkPlan>;

export function ReadLMXRegisters(arg1:Array<number>):Promise<gui.LMXRegisterReadResult>;

export function SaveTuningProfile(arg1:gui.TuningProfile):Promise<string>;

export function SetIPAddress(arg1:string):Promise<gui.NetworkChangeResult>;

export function SetMaximumAttenuation():Promise<gui.DeviceSnapshot>;

export function SetRFEnabled(arg1:boolean):Promise<gui.DeviceSnapshot>;

export function Version():Promise<string>;
