// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigureCW(arg1) {
  return window['go']['main']['App']['ConfigureCW'](arg1);
}

export function ConfigureSweep(arg1) {
  return window['go']['main']['App']['ConfigureSweep'](arg1);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function Discover() {
  return window['go']['main']['App']['Discover']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function PreviewNetwork(arg1) {
  return window['go']['main']['App']['PreviewNetwork'](arg1);
}

export function SetIPAddress(arg1) {
  return window['go']['main']['App']['SetIPAddress'](arg1);
}

export function SetMaximumAttenuation() {
  return window['go']['main']['App']['SetMaximumAttenuation']();
}
