# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: black_canyon.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'black_canyon.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x62lack_canyon.proto\x12\x15ocupoint.black_canyon\"/\n\x1cSetCalibrationEnabledRequest\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\"\x1f\n\x1dSetCalibrationEnabledResponse\",\n\x19SetChannelsEnabledRequest\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\"\x1c\n\x1aSetChannelsEnabledResponse\"/\n\x15SetAttenuationRequest\x12\x16\n\x0e\x61ttenuation_db\x18\x01 \x01(\x05\"\x18\n\x16SetAttenuationResponse\"\x12\n\x10GetStatusRequest\"b\n\x11GetStatusResponse\x12\x1b\n\x13\x63\x61libration_enabled\x18\x01 \x01(\x08\x12\x16\n\x0e\x61ttenuation_db\x18\x02 \x01(\x05\x12\x18\n\x10\x63hannels_enabled\x18\x03 \x01(\x08\"\xb2\x05\n\x06Packet\x12V\n\x17set_cal_enabled_request\x18\x01 \x01(\x0b\x32\x33.ocupoint.black_canyon.SetCalibrationEnabledRequestH\x00\x12X\n\x18set_cal_enabled_response\x18\x02 \x01(\x0b\x32\x34.ocupoint.black_canyon.SetCalibrationEnabledResponseH\x00\x12O\n\x17set_attenuation_request\x18\x03 \x01(\x0b\x32,.ocupoint.black_canyon.SetAttenuationRequestH\x00\x12X\n\x1cset_channels_enabled_request\x18\x04 \x01(\x0b\x32\x30.ocupoint.black_canyon.SetChannelsEnabledRequestH\x00\x12Q\n\x18set_attenuation_response\x18\x05 \x01(\x0b\x32-.ocupoint.black_canyon.SetAttenuationResponseH\x00\x12Z\n\x1dset_channels_enabled_response\x18\x06 \x01(\x0b\x32\x31.ocupoint.black_canyon.SetChannelsEnabledResponseH\x00\x12\x45\n\x12get_status_request\x18\x07 \x01(\x0b\x32\'.ocupoint.black_canyon.GetStatusRequestH\x00\x12G\n\x13get_status_response\x18\x08 \x01(\x0b\x32(.ocupoint.black_canyon.GetStatusResponseH\x00\x42\x0c\n\nmessage_idb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'black_canyon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETCALIBRATIONENABLEDREQUEST']._serialized_start=45
  _globals['_SETCALIBRATIONENABLEDREQUEST']._serialized_end=92
  _globals['_SETCALIBRATIONENABLEDRESPONSE']._serialized_start=94
  _globals['_SETCALIBRATIONENABLEDRESPONSE']._serialized_end=125
  _globals['_SETCHANNELSENABLEDREQUEST']._serialized_start=127
  _globals['_SETCHANNELSENABLEDREQUEST']._serialized_end=171
  _globals['_SETCHANNELSENABLEDRESPONSE']._serialized_start=173
  _globals['_SETCHANNELSENABLEDRESPONSE']._serialized_end=201
  _globals['_SETATTENUATIONREQUEST']._serialized_start=203
  _globals['_SETATTENUATIONREQUEST']._serialized_end=250
  _globals['_SETATTENUATIONRESPONSE']._serialized_start=252
  _globals['_SETATTENUATIONRESPONSE']._serialized_end=276
  _globals['_GETSTATUSREQUEST']._serialized_start=278
  _globals['_GETSTATUSREQUEST']._serialized_end=296
  _globals['_GETSTATUSRESPONSE']._serialized_start=298
  _globals['_GETSTATUSRESPONSE']._serialized_end=396
  _globals['_PACKET']._serialized_start=399
  _globals['_PACKET']._serialized_end=1089
# @@protoc_insertion_point(module_scope)
