# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: whalepod.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'whalepod.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ewhalepod.proto\x12\x11ocupoint.whalepod\"/\n\x1cSetCalibrationEnabledRequest\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\"\x1f\n\x1dSetCalibrationEnabledResponse\",\n\x19SetChannelsEnabledRequest\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\"\x1c\n\x1aSetChannelsEnabledResponse\"/\n\x15SetAttenuationRequest\x12\x16\n\x0e\x61ttenuation_db\x18\x01 \x01(\x05\"\x18\n\x16SetAttenuationResponse\"\x12\n\x10GetStatusRequest\"b\n\x11GetStatusResponse\x12\x1b\n\x13\x63\x61libration_enabled\x18\x01 \x01(\x08\x12\x16\n\x0e\x61ttenuation_db\x18\x02 \x01(\x05\x12\x18\n\x10\x63hannels_enabled\x18\x03 \x01(\x08\"\x92\x05\n\x06Packet\x12R\n\x17set_cal_enabled_request\x18\x01 \x01(\x0b\x32/.ocupoint.whalepod.SetCalibrationEnabledRequestH\x00\x12T\n\x18set_cal_enabled_response\x18\x02 \x01(\x0b\x32\x30.ocupoint.whalepod.SetCalibrationEnabledResponseH\x00\x12K\n\x17set_attenuation_request\x18\x03 \x01(\x0b\x32(.ocupoint.whalepod.SetAttenuationRequestH\x00\x12T\n\x1cset_channels_enabled_request\x18\x04 \x01(\x0b\x32,.ocupoint.whalepod.SetChannelsEnabledRequestH\x00\x12M\n\x18set_attenuation_response\x18\x05 \x01(\x0b\x32).ocupoint.whalepod.SetAttenuationResponseH\x00\x12V\n\x1dset_channels_enabled_response\x18\x06 \x01(\x0b\x32-.ocupoint.whalepod.SetChannelsEnabledResponseH\x00\x12\x41\n\x12get_status_request\x18\x07 \x01(\x0b\x32#.ocupoint.whalepod.GetStatusRequestH\x00\x12\x43\n\x13get_status_response\x18\x08 \x01(\x0b\x32$.ocupoint.whalepod.GetStatusResponseH\x00\x42\x0c\n\nmessage_idb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'whalepod_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETCALIBRATIONENABLEDREQUEST']._serialized_start=37
  _globals['_SETCALIBRATIONENABLEDREQUEST']._serialized_end=84
  _globals['_SETCALIBRATIONENABLEDRESPONSE']._serialized_start=86
  _globals['_SETCALIBRATIONENABLEDRESPONSE']._serialized_end=117
  _globals['_SETCHANNELSENABLEDREQUEST']._serialized_start=119
  _globals['_SETCHANNELSENABLEDREQUEST']._serialized_end=163
  _globals['_SETCHANNELSENABLEDRESPONSE']._serialized_start=165
  _globals['_SETCHANNELSENABLEDRESPONSE']._serialized_end=193
  _globals['_SETATTENUATIONREQUEST']._serialized_start=195
  _globals['_SETATTENUATIONREQUEST']._serialized_end=242
  _globals['_SETATTENUATIONRESPONSE']._serialized_start=244
  _globals['_SETATTENUATIONRESPONSE']._serialized_end=268
  _globals['_GETSTATUSREQUEST']._serialized_start=270
  _globals['_GETSTATUSREQUEST']._serialized_end=288
  _globals['_GETSTATUSRESPONSE']._serialized_start=290
  _globals['_GETSTATUSRESPONSE']._serialized_end=388
  _globals['_PACKET']._serialized_start=391
  _globals['_PACKET']._serialized_end=1049
# @@protoc_insertion_point(module_scope)
